### ISSUE TITLE
Default installation of Numpy breaks MOP-UP

### ISSUE THREAD

**Issue by nelsonruth11** [martinez-zacharya/MOP-UP#3]
Hello,

I installed MOP-UP following the directions in the readme. I then ran it on a small file with the command 

`python3 mop-up.py test /path/mve/mve_test.faa @ /path/analysis/mopup/mop_out/`

which immediately threw an error "AttributeError: module 'numpy' has no attribute 'bool'".

I downgraded Numpy to v1.23.5 (`conda install numpy=1.23.5`) and MOP-UP ran successfully. It appears as of Numpy 1.20 np.int and np.bool have been deprecated then entirely removed at version 1.24.0. 

Anyways, thanks for the tool and love the profile pic. 
-Nelson

**Comment by martinez-zacharya** [comment]
Thank you for finding this bug and also figuring out the fix! I've changed the .yml file to set up the conda environment to specifically use numpy=1.23.5.
