### ISSUE TITLE
Need help interpreting the output

### ISSUE THREAD

**Issue by nikolasbasler** [martinez-zacharya/MOP-UP#4]
Hello,

I am trying assign about 800 microviruses to the families you suggested and ran MOU-UP with all their proteins. It ran through without errors but I can't make sense of the output and would appreciate some help.

This is how I called the pipeline:
`python3 mop-up.py bphage_micros $VSC_SCRATCH/BPhage/tax_micros/bphage.microviridae.proteins.fasta @ \
    $VSC_SCRATCH/BPhage/tax_micros/bphage_micros_mopup --cpu $threads --miniden 30`

These are the first 3 sequences of my input fasta:
```
>NODE_A100_length_4425_cov_7.182613_PT_19410_aut_mid_d@NODE_A100_length_4425_cov_7.182613_PT_19410_aut_mid_d_CDS_0001
MQPFVGQSDKQVLSALSETINRDHTHAI
>NODE_A100_length_4425_cov_7.182613_PT_19410_aut_mid_d@NODE_A100_length_4425_cov_7.182613_PT_19410_aut_mid_d_CDS_0002
MGYYYRNKEASRTINTEPTLTDQAGARDTDINVIIGRFRRTGMVPVSQTQPMSGDFTALP
QDLRGYIEAAKQKELIRRKLPKELQEMAIEELLALTPEQLRQKLTPPETKKNPGG*
>NODE_A100_length_4425_cov_7.182613_PT_19410_aut_mid_d@NODE_A100_length_4425_cov_7.182613_PT_19410_aut_mid_d_CDS_0003
MGPLIPALIAGGASLIGGAMGNSAQSRANRTNIALQREQQAWEERMSNTSWQRGVEDMKA
AGLNPMLAYSQGGASTPSVSAATVQPVDALARGVTSAGSKATLAVETAQALANIELTKAS
ATRQAAEARTAQSNSAFADALNQAKLDLAKKEVEAVISRFQLNDEQRRQIHDLLPLMIQQ
YQNQAELTQAQTATEKARGQREEYSLPSAKAEAEVWEKLGAAGRGANIGANALQQIIAII
RSLGRN*
```

In the Master.csv, the "subgroup" of my genomes just seems to be a repetition of the genome name, so no assignment to any of the families.

I followed the instructions to visualise the network with Cytoscape and expected to see something similar to Figure 2A in your paper, with my genomes clustered with various groups. But instead I see something quite different: Before the suggested degree filtering, there are many disjoint sub-graphs with the genome in the middle and several genes connected to it, kind of star-shaped (see screenshot). When I then apply the degree filtering, only the genomes are left, without any connection between them.

Any help would be greatly appreciated.

Kind regards,
Nikolas

<img width="960" alt="Screenshot 2024-10-01 at 16 37 48" src="https://github.com/user-attachments/assets/44967253-6134-4e3a-af29-d734d62c1ea2">

**Comment by nikolasbasler** [comment]
I see the problem now. The documentation refers to the value for the parameter `--miniden` als 30 or 50, but looking at the `mop-up.py` the value should be a proportion, i.e. `0.30`. 

Running it like this gives a very different result that looks much more sensible on first glance.

**Comment by martinez-zacharya** [comment]
Thanks for finding this error in the documentation and for following up that you were able to get it working! The correct proportion format is now suggested in the README.
